FROM python:3.11-slim
WORKDIR /app
COPY protocol_client.py .
# use last asyncio-mqtt version with stable API; new aiomqtt 1.x breaks our client
RUN pip install "paho-mqtt==1.6.1" "asyncio-mqtt==0.12.1" aiocoap requests
CMD ["python","protocol_client.py"]
